function writeKernelFitResults(fitResults, time, folder, type)

if nargin < 2
    type = 'grating';
end

writeNPY(time.kernel, fullfile(folder, ...
    sprintf('_ss_%sKernels.timestamps.npy', type)))
writeNPY(cat(2, fitResults.kernel), fullfile(folder, ...
    sprintf('_ss_%sKernels.dff.npy', type)))
writeNPY(cat(3, fitResults.amplitudes), fullfile(folder, ...
    sprintf('_ss_%sTrials.amplitudes.npy', type)))
writeNPY(cat(1, fitResults.pValue), fullfile(folder, ...
    sprintf('_ss_%sFits.pValue.npy', type)))
writeNPY(cat(1, fitResults.R2), fullfile(folder, ...
    sprintf('_ss_%sFits.R2.npy', type)))
writeNPY(cat(2, fitResults.prediction), fullfile(folder, ...
    sprintf('_ss_%sPredictions.dff.npy', type)))
writeNPY(cat(2, time.prediction), fullfile(folder, ...
    sprintf('_ss_%sPredictions.timestamps.npy', type)))

if strcmp(type, 'bars')
    writeNPY(cat(3, fitResults.lags), fullfile(folder, ...
        sprintf('_ss_%sTrials.lags.npy', type)))
end